### ISSUE TITLE
Domain is mandatory in "I need..." steps. Why ?

### ISSUE THREAD

**Issue by yucer** [camptocamp/oerpscenario#32]
It seems to be no options to specify all the field values in the "and having" step.

Why?

**Comment by nbessi** [comment]
Because it uses a table and a custom DSL: 

      Scenario: Configure main  company
      Given I need a "res.company" with oid: base.main_company
        And having:
  
        | key         | value            |
        | name        | TOTO             |
        | street      | 21 jump street   |
        | street2     |                  |
        | zip         | 93310            |
        | city        | Springfields     |
        | country_id  | by code: US      |
        | phone       | 01 00000000      |
        | fax         | 01000000006      |
        | email       | contact@toto.com |
        | website     | www.toto.com     |
        | vat         | FRxxxxxxx        |
        | rml_header1 |                  |
        |             |                  |


If we take the previous example we see that the first sentence allows use to indentify one ore many resources: 
``Given I need a "res.company" with oid: base.main_company``
You can use the keyword ``need`` or ``find`` in conjuction with `a` or `all` to indentify a given resources set in bracket.  

The ``need`` will find or create/update a resource the ``find`` will raise an error if no resource founds

After the ``with`` you can set a domain to identify a resource
``with: oid base.main_company```refers to an Odoo XML id but here you can create your own domain:   

``with name: A_NAME and zip: A_zip and country_id by code: US``

This domain will identify a/many ressources that will be passed a argument to the 
``And having:`` directive.

That directive await a table with columns 
``| key | value |``

That will update the resource fields using oerpscenario DSL
